version: "3.9"

services:
  app:
    build: .
    container_name: vhuinfoseclab_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - vhuinfoseclab_net

  mongo:
    image: mongo:6
    container_name: vhuinfoseclab_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - vhuinfoseclab_net

volumes:
  mongo_data:

networks:
  vhuinfoseclab_net:
